### ISSUE TITLE
Spacing on peeps page is off

### ISSUE THREAD

**Issue by mroy93** [chiragjp/chiragjp.github.io#4]
Between current group members and past affiliates.  Currently there is an overlap on Yeran's picture with the third heading.   

Matt tried adding line breaks  before the heading to add space but it didn't effectively change anything.  Before I chop up the website, I figured I'd try posting an "issue" :smiley_cat:

**Comment by chiragjp** [comment]
almost… I think we ned to add an empty “person” block

**Comment by chiragjp** [comment]
fixed; added a padding for the bottom student profiles.
